[package]
name = "podgrabv2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version="0.11.14", features = ["blocking", "json", "async-compression", "rustls"]}
rusqlite= {version="0.28.0", features=["bundled", "chrono"]}
actix = "0.13.0"
actix-files = "0.6.2"
actix-web = "4.3.0"
chrono = "0.4.23"
actix-web-actors = "4.2.0"
actix-cors="0.6.4"
mp3-duration = "0.1.10"
feed-rs = "1.3"
regex = "1.7.1"
clokwerk= "0.4.0"
tokio = {version = "1.24.2", features = ["full"]}
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.93"
dotenv = "0.15.0"