[package]
name = "podgrabv2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version="0.11.14", features = ["blocking", "json", "async-compression", "rustls"]}
rusqlite= {version="0.28.0", features=["bundled", "chrono"]}
rocket = {version="0.4.11", features=["default"]}
feed-rs = "1.3"
regex = "1.7.1"
clokwerk= "0.4.0"
rocket_codegen = "0.4.11"
tokio = {version = "1.24.2", features = ["full"]}
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.93"
dotenv = "0.15.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json","serve"]