[target."aarch64-unknown-linux-gnu"]
#image.name="docker-registry.schwanzer.online/public/aarch64-unknown-linux-gnu:local"
#image.toolchain = ["x86_64-unknown-linux-gnu","linux/arm64=aarch64-unknown-linux-gnu"]
env.passthrough = ["RUSTFLAGS"]
pre-build = ["dpkg --add-architecture aarch64 && apt update && apt install postgres:aarch64 -y"]

[target."armv7-unknown-linux-gnueabihf"]
#image.name="docker-registry.schwanzer.online/public/armv7-unknown-linux-gnueabihf:local"
#image.toolchain = ["x86_64-unknown-linux-gnu","linux/arm64=aarch64-unknown-linux-gnu"]
env.passthrough = ["RUSTFLAGS"]
pre-build = ["dpkg --add-architecture armhf && apt update && apt install postgres:armhf -y"]

[target."x86_64-unknown-linux-gnu"]
#image.name="docker-registry.schwanzer.online/public/x86_64-unknown-linux-gnu:local"
#image.toolchain = ["x86_64-unknown-linux-gnu","linux/arm64=aarch64-unknown-linux-gnu"]
env.passthrough = ["RUSTFLAGS"]
pre-build = ["dpkg --add-architecture amd64 && apt update && apt install postgres:amd64 -y"]