[target."aarch64-unknown-linux-musl"]
image.name="docker-registry.schwanzer.online/dockerhub_proxy/blackdex/rust-musl:aarch64-musl-1.69.0"
image.toolchain = ["x86_64-unknown-linux-musl","linux/arm64=aarch64-unknown-linux-gnu"]
env.passthrough = ["RUSTFLAGS", "TARGET_CC=gcc"]

[target."armv7-unknown-linux-musleabihf"]
image.name="docker-registry.schwanzer.online/dockerhub_proxy/blackdex/rust-musl:armv7-musleabihf-stable-1.69.0"
image.toolchain = ["x86_64-unknown-linux-musl","linux/arm64=aarch64-unknown-linux-gnu"]
env.passthrough = ["RUSTFLAGS", "TARGET_CC=gcc"]

[target."x86_64-unknown-linux-musl"]
image.name="docker-registry.schwanzer.online/dockerhub_proxy/blackdex/rust-musl:x86_64-musl-stable-1.69.0"
image.toolchain = ["x86_64-unknown-linux-musl","linux/arm64=aarch64-unknown-linux-gnu"]
env.passthrough = ["RUSTFLAGS", "TARGET_CC=gcc"]
