name: Rust

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Install and Build
        env:
          NODE_OPTIONS: --max-old-space-size=32768
        run: |
            cd ui
            npm install
            npm run build-github
            cd ..
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/podgrabv2 && mv target/release/podgrabv2 target/release/podgrabv2_amd64
      - name: Copy to root
        run: cp target/release/podgrabv2_amd64 .
      - name: zip
        run: zip -r podfetch-linux.zip podgrabv2_amd64 db static migrations LICENSE README.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            podfetch-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Install and Build
        env:
          NODE_OPTIONS: --max-old-space-size=32768
        run: |
          cd ui
          npm install
          npm run build-github
          cd ..
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release
      - name: Copy to root
        run: cp target/release/podgrabv2.exe .
      - name: Zip
        run: 7za -tzip podfetch-win.zip podgrabv2.exe db static migrations LICENSE README.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            podfetch-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Install and Build
        env:
          NODE_OPTIONS: --max-old-space-size=32768
        run: |
          cd ui
          npm install
          npm run build-github
          cd ..
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/podgrabv2 && mv target/release/podgrabv2 target/release/podgrabv2_darwin
      - name: Copy to root
        run: cp target/release/podgrabv2_darwin .
      - name: Zip
        run: zip -r podfetch-apple.zip podgrabv2_darwin db static migrations LICENSE README.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            podfetch-apple.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}